// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMRtdr6r7q2Zdfah3sUOtrQofkn9Z5vO0',
    appId: '1:540774492642:web:36770dbb23c97f3e0f71bb',
    messagingSenderId: '540774492642',
    projectId: 'whispher-12a57',
    authDomain: 'whispher-12a57.firebaseapp.com',
    storageBucket: 'whispher-12a57.appspot.com',
    measurementId: 'G-WRTVTEG541',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSSOIFpGlnAC6R5w17ayjRcFGj5PR60jo',
    appId: '1:540774492642:android:bafe949ad80459c70f71bb',
    messagingSenderId: '540774492642',
    projectId: 'whispher-12a57',
    storageBucket: 'whispher-12a57.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnX9INE_Hy5N2nIXDPMFYNSpfD54tiV2o',
    appId: '1:540774492642:ios:4ced30b8b61864c90f71bb',
    messagingSenderId: '540774492642',
    projectId: 'whispher-12a57',
    storageBucket: 'whispher-12a57.appspot.com',
    iosBundleId: 'com.example.whisfer',
  );
}
